#!/usr/bin/env node
/**
 * Catalogue refresh - assembles a review report of candidate new tells. Self-contained:
 * no API keys, no private infra. Two public, reproducible sources:
 *
 *   1. Corpus discovery   - slop-lint --discover over corpus/samples vs corpus/baseline.
 *   2. Wikipedia          - the maintained "Signs of AI writing" essay's "Words to watch",
 *                           diffed against our catalogue to surface coverage gaps.
 *
 * Writes refresh-report.md and prints a summary. Run monthly by
 * .github/workflows/catalogue-refresh.yml, which files the report as a GitHub issue.
 * Network failures are non-fatal (the corpus half still runs). Nothing auto-updates the
 * catalogue: a human reviews the report and adds the real tells with a source.
 *
 *   node refresh.mjs
 */

import { writeFileSync, existsSync } from "node:fs";
import { discover, WORDS, PHRASES, VERSION } from "./slop-lint.mjs";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const known = new Set(WORDS.map((w) => w.toLowerCase()));

function readDir(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  const walk = (d) => {
    for (const e of readdirSync(d)) {
      const p = join(d, e);
      if (statSync(p).isDirectory()) walk(p);
      else if (/\.(md|markdown|mdx|txt)$/.test(e)) { try { out.push(readFileSync(p, "utf8")); } catch { /* skip */ } }
    }
  };
  walk(dir);
  return out;
}

// ── 1. Corpus discovery ────────────────────────────────────────────────────────
function corpusSection() {
  const samples = readDir("corpus/samples"), baseline = readDir("corpus/baseline");
  if (!samples.length || !baseline.length) {
    return "## Corpus discovery\n\n_Skipped: add text to `corpus/samples` (model output) and `corpus/baseline` (human) and re-run._\n";
  }
  const cands = discover(samples, baseline, { top: 25 });
  if (!cands.length) return "## Corpus discovery\n\n_No over-represented tokens above threshold._\n";
  const rows = cands.map((c) => `| ${c.token} | ${c.count} | ${c.ratio.toFixed(1)}× |`).join("\n");
  return `## Corpus discovery\n\nOver-represented in \`corpus/samples\` vs \`corpus/baseline\`, not in the catalogue:\n\n` +
    `| candidate | count | over-representation |\n|---|---:|---:|\n${rows}\n`;
}

// ── 2. Wikipedia "Signs of AI writing" ─────────────────────────────────────────
async function wikipediaSection() {
  const url = "https://en.wikipedia.org/w/api.php?action=parse&page=Wikipedia:Signs_of_AI_writing&prop=wikitext&format=json&formatversion=2";
  let wikitext;
  try {
    const res = await fetch(url, { headers: { "User-Agent": "slop-lint catalogue-refresh (https://github.com/eric-sabe/slop-lint)" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    wikitext = (await res.json()).parse.wikitext;
  } catch (e) {
    return `## Wikipedia: Signs of AI writing\n\n_Source unavailable this run (${e.message}); corpus half still ran._\n`;
  }
  // Extract the italic items inside each "Words to watch: {{strong|''a'', ''b''}}".
  const items = new Set();
  for (const m of wikitext.matchAll(/Words to watch:\s*\{\{strong\|([^}]*)\}\}/gi)) {
    for (const it of m[1].matchAll(/''([^'']+)''/g)) {
      const phrase = it[1].replace(/\[\[|\]\]/g, "").trim().toLowerCase();
      if (phrase && phrase.length < 60) items.add(phrase);
    }
  }
  if (!items.size) return "## Wikipedia: Signs of AI writing\n\n_No parseable 'Words to watch' items this run (page format may have changed)._\n";
  // A phrase is a coverage gap if no existing phrase rule matches it and none of its
  // content words are already in WORDS.
  const gaps = [...items].filter((phrase) => {
    if (PHRASES.some((p) => p.re.test(phrase))) return false;
    const toks = phrase.match(/[a-z][a-z'-]{3,}/g) || [];
    return toks.length && !toks.some((t) => known.has(t));
  }).sort();
  const body = gaps.length
    ? gaps.map((g) => `- ${g}`).join("\n")
    : "_All current 'Words to watch' are already covered by the catalogue._";
  return `## Wikipedia: Signs of AI writing\n\n${items.size} "Words to watch" items found; ${gaps.length} not yet covered by our catalogue:\n\n${body}\n`;
}

// ── Assemble ────────────────────────────────────────────────────────────────────
const stamp = process.env.REFRESH_DATE || "this run"; // CI passes a date; keep deterministic otherwise
const report = `# slop-lint catalogue refresh

Candidate new tells for review (catalogue v${VERSION}, ${stamp}). Nothing here is added automatically: confirm a tell is real, add it to \`WORD_GROUPS\` / \`PHRASES\` with a source, note it in \`CHANGELOG.md\`, and bump the version. Prune any catalogue entries that have faded.

${corpusSection()}
${await wikipediaSection()}
---
_Generated by \`refresh.mjs\`. Sources: corpus frequency analysis + Wikipedia:Signs of AI writing._
`;

writeFileSync("refresh-report.md", report);
console.log(report);
